Repository epam/corgis, pull requests merged in 2021-03, with the labels that each got.

#187 Features/186 input autofocus
  src/modules/common/Input/Input.jsx
  src/modules/common/corgi/actions/CorgiActions/CorgiActions.jsx
  src/modules/common/corgi/actions/Transfer/Transfer.jsx
  src/modules/common/corgi/actions/popups/DeletePopup.jsx
  src/modules/common/popups/Popup/Popup.scss
  src/modules/common/popups/PopupWrapper/PopupWrapper.jsx
  src/modules/minting/components/MintingForm/MintingForm.jsx
Labels: FE, enhancement

#188 Features/144 any user corgis list
  src/App.jsx
  src/contexts/contract/index.js
  src/helpers/checkAccountLegit.js
  src/modules/account/page/AccountPage.jsx
  src/modules/account/page/index.js
  src/modules/common/Input/Input.jsx
  src/modules/common/corgi/Owner/Owner.jsx
  src/modules/common/corgi/Owner/Owner.scss
  src/modules/common/corgi/actions/Transfer/Transfer.jsx
  src/modules/common/popups/Popup/Popup.scss
  src/modules/common/popups/PopupWrapper/PopupWrapper.jsx
  src/modules/header/Nav/Nav.jsx
  src/modules/share/components/.gitkeep
  src/modules/share/page/SharePage.jsx
  src/modules/share/page/SharePage.scss
  src/modules/user/components/.gitkeep
  src/modules/user/page/UserPage.jsx
  src/modules/user/page/UserPage.scss
  src/modules/user/page/index.js
  src/router/Routes.jsx
  src/styles/_classes.scss
Labels: FE, enhancement

#189 Features/154 minting animation
  src/hooks/index.js
  src/hooks/useInterval.js
  src/modules/common/corgi/CorgiAnimations/CorgiAnim.scss
  src/modules/common/corgi/CorgiAnimations/CorgiAnimFour.jsx
  src/modules/common/corgi/CorgiAnimations/CorgiAnimOne.jsx
  src/modules/common/corgi/CorgiAnimations/CorgiAnimThree.jsx
  src/modules/common/corgi/CorgiAnimations/CorgiAnimTwo.jsx
  src/modules/common/corgi/CorgiAnimations/index.js
  src/modules/common/corgi/actions/popups/DeletePopup.jsx
  src/modules/minting/components/MintingAnimation/MintingAnimation.jsx
  src/modules/minting/components/MintingAnimation/MintingAnimation.scss
  src/modules/minting/page/MintingPage.jsx
  src/modules/user/page/UserPage.jsx
  src/styles/_variables.scss
Labels: FE, enhancement, styling

#190 Upgrade/176 near api js
  package.json
  src/index.js
  yarn.lock
Labels: FE

#192 Features/175 use react color instead of html colorpicker
  package.json
  src/modules/common/Colorpicker/Colorpicker.jsx
  src/modules/common/Colorpicker/Colorpicker.scss
  yarn.lock
Labels: FE, styling

#196 Features/195 async corgis animation
  src/helpers/generators/genRandomInt.js
  src/helpers/generators/index.js
  src/modules/common/corgi/CorgiSVG/CorgiSVG.jsx
  src/modules/common/corgi/CorgiSVG/CorgiSVG.scss
  src/styles/_animations.scss
Labels: FE, styling

#191 Features/173 sharing image and name
  src/contexts/corgiActions/index.js
  src/contexts/index.js
  src/modules/common/corgi/CorgiCard/CorgiCard.jsx
  src/modules/common/corgi/actions/CorgiActions/CorgiActions.jsx
  src/modules/common/corgi/actions/Share/Share.jsx
  src/modules/common/corgi/actions/Transfer/Transfer.jsx
  src/modules/common/corgi/actions/popups/DeletePopup.jsx
  src/modules/common/corgi/actions/popups/GiftPopup.jsx
  src/modules/common/corgi/actions/popups/SharePopup.jsx
Labels: FE, enhancement

#201 Features/173 sharing image and name
  src/contexts/corgiActions/index.js
  src/contexts/index.js
  src/modules/common/corgi/CorgiCard/CorgiCard.jsx
  src/modules/common/corgi/actions/CorgiActions/CorgiActions.jsx
  src/modules/common/corgi/actions/Share/Share.jsx
  src/modules/common/corgi/actions/Transfer/Transfer.jsx
  src/modules/common/corgi/actions/popups/DeletePopup.jsx
  src/modules/common/corgi/actions/popups/GiftPopup.jsx
  src/modules/common/corgi/actions/popups/SharePopup.jsx
  src/modules/corgi/page/CorgiPage.jsx
Labels: FE, enhancement

#202 Fixup/hide popup on delete issue
  src/modules/common/corgi/actions/popups/DeletePopup.jsx
  src/modules/corgi/page/CorgiPage.jsx
Labels: FE, bug

#194 Refactor/193 remove unnecessary packages
  package.json
  src/helpers/generators/genRandomCharacter.js
  src/helpers/generators/genRandomColor.js
  src/helpers/generators/index.js
  src/modules/minting/components/MintingForm/MintingForm.jsx
  yarn.lock
Labels: FE, refactor

#203 Features/share corgi svg
  package.json
  src/App.jsx
  src/contexts/contract/index.js
  src/modules/common/corgi/CorgiPNG/CorgiPNG.jsx
  src/modules/common/corgi/CorgiPNG/index.js
  src/modules/common/corgi/CorgiSVG/CorgiSVG.jsx
  src/modules/common/corgi/actions/Share/Share.jsx
  src/modules/common/corgi/index.js
  src/modules/corgi/page/CorgiPage.jsx
  src/router/Routes.jsx
  yarn.lock
Labels: FE, enhancement

#204 Features/share corgi svg v2
  src/modules/common/corgi/CorgiPNG/CorgiPNG.jsx
  src/modules/common/corgi/CorgiSVG/CorgiSVG.jsx
  src/modules/common/corgi/CorgiSVG/CorgiSVG.scss
Labels: FE, enhancement

#205 Fixup/path to shared image
  src/modules/common/corgi/actions/Share/Share.jsx
Labels: FE, bug

#212 Features/161 withdraw button
  src/App.jsx
  src/constants/corgi/ActionMessages.js
  src/modules/common/Donation/Donation.jsx
  src/modules/common/corgi/CorgisShowCase/CorgisShowCase.jsx
  src/modules/common/corgi/actions/CorgiActions/CorgiActions.jsx
  src/modules/common/corgi/actions/index.js
  src/modules/common/corgi/actions/popups/WithdrawPopup.jsx
  src/modules/common/corgi/actions/popups/index.js
  src/modules/common/corgi/index.js
  src/modules/corgi/components/AuctionCard/AuctionCard.jsx
  src/modules/home/page/HomePage.jsx
Labels: FE, enhancement

#217 Features/214 finish auction button for the highest bidder
  src/modules/corgi/components/AuctionCard/AuctionCard.jsx
  src/modules/corgi/components/ClearanceButton/ClearanceButton.jsx
  src/modules/corgi/components/ClearanceButton/index.js
  src/modules/corgi/components/index.js
  src/types/NearTypes/index.js
Labels: FE, enhancement

#222 Fixup/221 float bid display
  src/modules/common/corgi/auction/BidAmount/BidAmount.jsx
  src/modules/corgi/components/BidInput/BidInput.jsx
Labels: FE, bug

#224 fixup/219 Sort items in marketplace depending on auction end time
  src/modules/marketplace/page/MarketplacePage.jsx
Labels: FE, enhancement

#223 Fixup/220 convert time ago from hours into days and hours
  src/modules/common/corgi/Activity/Activity.jsx
  src/modules/common/corgi/auction/HighestBid/HighestBid.jsx
  src/modules/corgi/components/BidTile/BidTile.jsx
Labels: FE, enhancement
